--CREATE SCHEMA IF NOT EXISTS resilience;

CREATE TABLE outbox
(
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    destination varchar   NOT NULL,
    message     bytea     NOT NULL,
    class       varchar   NOT NULL,
    emitted_on  timestamp NOT NULL,
    processed   boolean DEFAULT FALSE
);